spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/demo?authSource=admin
      auto-index-creation: true

mongock:
  migration-scan-package:
    - com.soft2run.queries.migration

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG