server:
  port: 8083

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  application:
    name: gateway
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
#      rate: 2
#      probability: 0.1
    web:
      skipPattern: /gateway/ok