server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  application:
    name: station
  zipkin:
    baseUrl: http://localhost:9411
