server:
  port: 0

spring:
  application:
    name: vehicle

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
  client:
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health