server:
  port: 0

spring:
  application:
    name: station

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
  client:
    registerWithEureka: true
    fetchRegistry: true
