server:
  port: 8080

spring:
  application:
    name: kafka-stream
  cloud:
    stream:
      bindings:
        produceStation-out-0:
          destination: station-topic
          content-type: application/json
#          producer:
#            partition-key-expression: headers.version
#            partition-count: 2
        produceStations-out-0:
          destination: station-topic
          content-type: application/json
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: business-service
