server:
  port: 8081

spring:
  cloud:
    config:
      name: app1
      profile: dev
      label: develop
  config:
    import: optional:configserver:http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: refresh

encrypt:
  key: 1234