server:
  port: 7999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: get_station_v1
          uri: http://localhost:8080
          predicates:
            - Method=GET
            - Path=/v1/station/{id}
          filters:
            - SetPath=/station/{id}
        - id: get_station_v2
          uri: http://localhost:8081
          predicates:
            - Method=GET
            - Path=/v2/station/{id}
          filters:
            - SetPath=/station/{id}
